# -*- coding: utf-8 -*-
"""Examen_CristobalH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezIBZJqupxamrP-HPeVbaCo42qh7O_0g
"""

# Clase Contacto
class Contacto:
    def __init__(self, nombre, telefono, correo, direccion):
        self.nombre = nombre
        self.telefono = telefono
        self.correo = correo
        self.direccion = direccion


# Lista para almacenar contactos
contactos = []


# Agregar contacto
def agregar_contacto(nombre, telefono, correo, direccion):
    contacto = Contacto(nombre, telefono, correo, direccion)
    contactos.append(contacto)
    print("Contacto agregado correctamente.")


# Listar contactos
def listar_contactos():
    for c in contactos:
        print("Nombre:", c.nombre)
        print("Teléfono:", c.telefono)
        print("Correo:", c.correo)
        print("Dirección:", c.direccion)
        print("--------------------")


# Buscar contacto por nombre
def buscar_contacto(nombre):
    for c in contactos:
        if c.nombre.lower() == nombre.lower():
            print("Contacto encontrado:")
            print(c.nombre, c.telefono, c.correo, c.direccion)
            return
    print("Contacto no encontrado.")


# Eliminar contacto
def eliminar_contacto(nombre):
    for c in contactos:
        if c.nombre.lower() == nombre.lower():
            contactos.remove(c)
            print("Contacto eliminado.")
            return
    print("Contacto no encontrado.")


# -------------------------
# Cargar 5 contactos iniciales
# -------------------------
agregar_contacto("Ana Torres", "1111111", "ana@mail.com", "Calle 1")
agregar_contacto("Carlos Perez", "2222222", "carlos@mail.com", "Calle 2")
agregar_contacto("Lucia Rojas", "3333333", "lucia@mail.com", "Calle 3")
agregar_contacto("Juan Soto", "4444444", "juan@mail.com", "Calle 4")
agregar_contacto("Maria Lopez", "5555555", "maria@mail.com", "Calle 5")


# Menú principal
while True:
    print("\nSistema de Gestión de Contactos")
    print("1. Agregar contacto")
    print("2. Listar contactos")
    print("3. Buscar contacto")
    print("4. Eliminar contacto")
    print("5. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        nombre = input("Nombre: ")
        telefono = input("Teléfono: ")
        correo = input("Correo: ")
        direccion = input("Dirección: ")
        agregar_contacto(nombre, telefono, correo, direccion)

    elif opcion == "2":
        listar_contactos()

    elif opcion == "3":
        nombre = input("Nombre a buscar: ")
        buscar_contacto(nombre)

    elif opcion == "4":
        nombre = input("Nombre a eliminar: ")
        eliminar_contacto(nombre)

    elif opcion == "5":
        print("Saliendo del sistema...")
        break

    else:
        print("Opción no válida.")